### ISSUE TITLE
Double standards

### ISSUE THREAD

**Issue by BinaryFocus** [consenlabs/eos-bp-profile#17]
I am currently producing  a BP JSON file which is very similar to the one described in this repo, but not exactly. 

https://github.com/EOSPortal/bp-info-standard
https://github.com/eosrio/bp-info-standard

Note that this EOS BP standard has a Schema, so I've written a small app that produces my JSON and validates it against the provided schema. 

While I could (and will if that's your desire) produce another JSON file to your spec, I feel you may want to consider using this other spec and it's schema file. This will allow people to validate their JSON before providing it to you  ... it also mean we have one standard and not 10 :)  ... 

Let me know what you think please. I think think this will also save you a lot of trouble in the future.

**Comment by Xaber20110202** [comment]
Hi, Thank you for your advice.

We have considered this part of schema before, but because of our own business considerations, we have used our own specification.

https://github.com/consenlabs/eos-bp-profile/blob/master/src/schema.json
https://github.com/consenlabs/eos-bp-profile/blob/master/bp/%24template.json

We added schema validations, and will integrate the travils-ci to do the validations automatically.
